./spl ../labs/27/bootmodule.spl
./spl ../labs/27/devicemanager.spl
./spl ../labs/27/processmanager.spl
./spl ../labs/27/memorymanager.spl
./spl ../labs/27/filemanager.spl
./spl ../labs/27/os_startup.spl
./spl ../labs/27/resourcemanager.spl
./spl ../labs/27/pagermodule.spl
./spl ../labs/27/scheduler.spl
./spl ../labs/27/timer.spl
./spl ../labs/27/exhandler.spl
./spl ../labs/27/int4.spl
./spl ../labs/27/int5.spl
./spl ../labs/27/int6.spl
./spl ../labs/27/int7.spl
./spl ../labs/27/int8.spl
./spl ../labs/27/int9.spl
./spl ../labs/27/int10.spl
./spl ../labs/27/int11.spl
./spl ../labs/27/int12.spl
./spl ../labs/27/int13.spl
./spl ../labs/27/int14.spl
./spl ../labs/27/int15.spl
./spl ../labs/27/int16.spl
./spl ../labs/27/int17.spl
./spl ../labs/27/diskint.spl
./spl ../labs/27/consoleinterrupt.spl