./spl ../labs/16/bootmodule.spl
./spl ../labs/16/bootmodule16.spl
./spl ../labs/16/devicemanager.spl
./spl ../labs/16/exception.spl
./spl ../labs/16/int7.spl
./spl ../labs/16/int10.spl
./spl ../labs/16/os_startup.spl
./spl ../labs/16/resourcemanager.spl
./spl ../labs/16/scheduler.spl
./spl ../labs/16/timer.spl
./spl ../labs/16/int6.spl
./spl ../labs/16/consoleinterrupt.spl