./spl ../labs/22/bootmodule.spl
./spl ../labs/22/devicemanager.spl
./spl ../labs/22/processmanager.spl
./spl ../labs/22/memorymanager.spl
./spl ../labs/22/os_startup.spl
./spl ../labs/22/resourcemanager.spl
./spl ../labs/22/scheduler.spl
./spl ../labs/22/timer.spl
./spl ../labs/22/exhandler.spl
./spl ../labs/22/int6.spl
./spl ../labs/22/int7.spl
./spl ../labs/22/int8.spl
./spl ../labs/22/int9.spl
./spl ../labs/22/int10.spl
./spl ../labs/22/int11.spl
./spl ../labs/22/int13.spl
./spl ../labs/22/int14.spl
./spl ../labs/22/int15.spl
./spl ../labs/22/diskint.spl
./spl ../labs/22/consoleinterrupt.spl