./spl ../labs/24/bootmodule.spl
./spl ../labs/24/devicemanager.spl
./spl ../labs/24/processmanager.spl
./spl ../labs/24/memorymanager.spl
./spl ../labs/24/filemanager.spl
./spl ../labs/24/os_startup.spl
./spl ../labs/24/resourcemanager.spl
./spl ../labs/24/scheduler.spl
./spl ../labs/24/timer.spl
./spl ../labs/24/exhandler.spl
./spl ../labs/24/int4.spl
./spl ../labs/24/int5.spl
./spl ../labs/24/int6.spl
./spl ../labs/24/int7.spl
./spl ../labs/24/int8.spl
./spl ../labs/24/int9.spl
./spl ../labs/24/int10.spl
./spl ../labs/24/int11.spl
./spl ../labs/24/int13.spl
./spl ../labs/24/int14.spl
./spl ../labs/24/int15.spl
./spl ../labs/24/diskint.spl
./spl ../labs/24/consoleinterrupt.spl