./spl ../labs/26/bootmodule.spl
./spl ../labs/26/devicemanager.spl
./spl ../labs/26/processmanager.spl
./spl ../labs/26/memorymanager.spl
./spl ../labs/26/filemanager.spl
./spl ../labs/26/os_startup.spl
./spl ../labs/26/resourcemanager.spl
./spl ../labs/26/scheduler.spl
./spl ../labs/26/timer.spl
./spl ../labs/26/exhandler.spl
./spl ../labs/26/int4.spl
./spl ../labs/26/int5.spl
./spl ../labs/26/int6.spl
./spl ../labs/26/int7.spl
./spl ../labs/26/int8.spl
./spl ../labs/26/int9.spl
./spl ../labs/26/int10.spl
./spl ../labs/26/int11.spl
./spl ../labs/26/int12.spl
./spl ../labs/26/int13.spl
./spl ../labs/26/int14.spl
./spl ../labs/26/int15.spl
./spl ../labs/26/int16.spl
./spl ../labs/26/int17.spl
./spl ../labs/26/diskint.spl
./spl ../labs/26/consoleinterrupt.spl