./spl ../labs/25/bootmodule.spl
./spl ../labs/25/devicemanager.spl
./spl ../labs/25/processmanager.spl
./spl ../labs/25/memorymanager.spl
./spl ../labs/25/filemanager.spl
./spl ../labs/25/os_startup.spl
./spl ../labs/25/resourcemanager.spl
./spl ../labs/25/scheduler.spl
./spl ../labs/25/timer.spl
./spl ../labs/25/exhandler.spl
./spl ../labs/25/int4.spl
./spl ../labs/25/int5.spl
./spl ../labs/25/int6.spl
./spl ../labs/25/int7.spl
./spl ../labs/25/int8.spl
./spl ../labs/25/int9.spl
./spl ../labs/25/int10.spl
./spl ../labs/25/int11.spl
./spl ../labs/25/int13.spl
./spl ../labs/25/int14.spl
./spl ../labs/25/int15.spl
./spl ../labs/25/diskint.spl
./spl ../labs/25/consoleinterrupt.spl