./spl ../labs/23/bootmodule.spl
./spl ../labs/23/devicemanager.spl
./spl ../labs/23/processmanager.spl
./spl ../labs/23/memorymanager.spl
./spl ../labs/23/os_startup.spl
./spl ../labs/23/resourcemanager.spl
./spl ../labs/23/scheduler.spl
./spl ../labs/23/timer.spl
./spl ../labs/23/exhandler.spl
./spl ../labs/23/int4.spl
./spl ../labs/23/int6.spl
./spl ../labs/23/int7.spl
./spl ../labs/23/int8.spl
./spl ../labs/23/int9.spl
./spl ../labs/23/int10.spl
./spl ../labs/23/int11.spl
./spl ../labs/23/int13.spl
./spl ../labs/23/int14.spl
./spl ../labs/23/int15.spl
./spl ../labs/23/diskint.spl
./spl ../labs/23/consoleinterrupt.spl