./spl ../labs/21/bootmodule.spl
./spl ../labs/21/devicemanager.spl
./spl ../labs/21/processmanager.spl
./spl ../labs/21/memorymanager.spl
./spl ../labs/21/os_startup.spl
./spl ../labs/21/resourcemanager.spl
./spl ../labs/21/scheduler.spl
./spl ../labs/21/timer.spl
./spl ../labs/21/exhandler.spl
./spl ../labs/21/int6.spl
./spl ../labs/21/int7.spl
./spl ../labs/21/int8.spl
./spl ../labs/21/int9.spl
./spl ../labs/21/int10.spl
./spl ../labs/21/int11.spl
./spl ../labs/21/int15.spl
./spl ../labs/21/diskint.spl
./spl ../labs/21/consoleinterrupt.spl